eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: eurekaclient
  #链路跟踪 
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler: #采样请求百分比 默认为10%
      percentage: 1.0
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
 

